using Content.Client.Message;
using Content.Shared._FreakyStation.ERP;
using Content.Shared.Humanoid;
using Content.Shared.IdentityManagement;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._FreakyStation.ERP;

[GenerateTypedNameReferences]
public sealed partial class ERPUI : DefaultWindow
{
    private static readonly Color LowArousalColor = Color.FromHex("#4E8FB6");
    private static readonly Color HighArousalColor = Color.FromHex("#C34A66");

    private readonly SpriteSystem _spriteSystem;

    [Dependency] private readonly EntityManager _entManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly ERPEUI _eui;
    private int? _hoveredInteractionIndex;

    public NetEntity? TargetEntityId { get; set; }
    public ERPPanelMode Mode { get; set; }
    public TimeSpan CooldownEndTime { get; set; }
    public Sex UserSex { get; set; }
    public Sex TargetSex { get; set; }
    public bool UserHasClothing { get; set; }
    public bool TargetHasClothing { get; set; }
    public ERPConsent UserConsent { get; set; }
    public ERPConsent TargetConsent { get; set; }
    public bool UserNonCon { get; set; }
    public bool TargetNonCon { get; set; }
    public float UserArousal { get; set; }
    public float TargetArousal { get; set; }
    public List<ERPInteractionEntryState> Interactions { get; set; } = new();

    public ERPUI(ERPEUI eui)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _spriteSystem = _entManager.System<SpriteSystem>();
        _eui = eui;

        SearchBar.OnTextChanged += _ => PopulateByFilter(SearchBar.Text);
        ItemInteractions.OnItemSelected += _eui.OnItemSelect;
        ItemInteractions.OnItemHover += OnInteractionHover;
        ItemInteractions.OnMouseExited += _ =>
        {
            _hoveredInteractionIndex = null;
            ItemInteractions.HideTooltip();
        };
        ItemInteractions.TooltipSupplier = SupplyInteractionTooltip;
        ItemInteractions.TooltipDelay = 0f;
    }

    public void Populate()
    {
        Title = Loc.GetString(Mode == ERPPanelMode.Self
            ? "erp-ui-title-self"
            : "erp-ui-title-target");

        PopulateCards();
        PopulateByFilter(SearchBar.Text);
        UpdateCooldown();
    }

    private void PopulateByFilter(string filter)
    {
        _hoveredInteractionIndex = null;
        ItemInteractions.HideTooltip();
        ItemInteractions.Clear();

        foreach (var interaction in Interactions)
        {
            if (!_prototypeManager.TryIndex(interaction.InteractionId, out var prototype))
                continue;

            if (!string.IsNullOrWhiteSpace(filter)
                && !prototype.Name.Contains(filter.Trim(), StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var texture = _spriteSystem.Frame0(prototype.Icon);
            var item = ItemInteractions.AddItem(prototype.Name, texture, metadata: interaction);
            ApplyInteractionAvailability(item);
        }

        UpdateCooldown();
    }

    private void PopulateCards()
    {
        if (!_player.LocalEntity.HasValue)
            return;

        var user = _player.LocalEntity.Value;
        var target = TargetEntityId.HasValue ? _entManager.GetEntity(TargetEntityId.Value) : user;

        UserCardHeading.Text = Loc.GetString("erp-ui-you-heading");
        UserCardDetails.SetMarkup(BuildEntityCardMarkup(UserSex, UserHasClothing, UserConsent, UserNonCon));
        UpdateArousalBar(UserArousalBar, UserArousalValue, UserArousal);

        TargetCardHeading.Text = Mode == ERPPanelMode.Self
            ? Loc.GetString("erp-ui-visible-to-others-heading")
            : Loc.GetString("erp-ui-target-heading", ("target", Identity.Name(target, _entManager, user)));
        TargetCardDetails.SetMarkup(BuildEntityCardMarkup(TargetSex, TargetHasClothing, TargetConsent, TargetNonCon));
        UpdateArousalBar(TargetArousalBar, TargetArousalValue, TargetArousal);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCooldown();
    }

    private void UpdateCooldown()
    {
        if (_timing.CurTime >= CooldownEndTime)
        {
            CooldownLabel.Visible = false;
            foreach (var item in ItemInteractions)
            {
                ApplyInteractionAvailability(item);
            }

            return;
        }

        var timeLeft = CooldownEndTime - _timing.CurTime;
        CooldownLabel.SetMarkup(Loc.GetString("erp-ui-cooldown", ("time", FormatCooldown(timeLeft))));
        CooldownLabel.Visible = true;
        ItemInteractions.ClearSelected();
        var cooldownReason = Loc.GetString("erp-ui-denied-reason-cooldown");
        foreach (var item in ItemInteractions)
        {
            item.Disabled = true;
            item.TooltipText = cooldownReason;
            item.TooltipEnabled = true;
        }
    }

    private string BuildEntityCardMarkup(Sex sex, bool hasClothing, ERPConsent consent, bool nonCon)
    {
        var lines = new List<string>
        {
            FormatInfoLine("erp-ui-sex-label", Loc.GetString(GetSexLocalizationKey(sex))),
            FormatInfoLine("erp-ui-clothing-label", FormatClothingMarkup(hasClothing)),
            FormatInfoLine("erp-ui-consent-label", ERPFormatting.FormatConsentMarkup(consent)),
            FormatInfoLine("erp-ui-non-con-label", ERPFormatting.FormatNonConMarkup(nonCon)),
        };

        return string.Join("\n", lines);
    }

    private static string FormatInfoLine(string labelKey, string valueMarkup)
    {
        return $"[bold]{FormattedMessage.EscapeText(Loc.GetString(labelKey))}[/bold] {valueMarkup}";
    }

    private static string GetSexLocalizationKey(Sex sex)
    {
        return sex switch
        {
            Sex.Male => "humanoid-profile-editor-sex-male-text",
            Sex.Female => "humanoid-profile-editor-sex-female-text",
            _ => "humanoid-profile-editor-sex-unsexed-text",
        };
    }

    private static string FormatClothingMarkup(bool hasClothing)
    {
        var labelKey = hasClothing ? "erp-ui-clothing-on" : "erp-ui-clothing-off";
        var color = hasClothing ? "gray" : "cyan";
        return ERPFormatting.FormatMarkup(Loc.GetString(labelKey), color);
    }

    private static void UpdateArousalBar(ProgressBar bar, Label valueLabel, float arousal)
    {
        var clamped = Math.Clamp(arousal, 0f, 1f);
        bar.Value = clamped;
        valueLabel.Text = Loc.GetString("erp-ui-arousal-value", ("value", (int) MathF.Round(clamped * 100f)));

        if (bar.ForegroundStyleBoxOverride is not StyleBoxFlat fill)
        {
            fill = new StyleBoxFlat();
            bar.ForegroundStyleBoxOverride = fill;
        }

        fill.BackgroundColor = Color.InterpolateBetween(LowArousalColor, HighArousalColor, clamped);
    }

    private void ApplyInteractionAvailability(ItemList.Item item)
    {
        if (item.Metadata is not ERPInteractionEntryState interaction)
        {
            item.Disabled = false;
            item.TooltipText = null;
            item.TooltipEnabled = false;
            return;
        }

        item.Disabled = !interaction.Enabled;
        item.TooltipText = interaction.Enabled
            ? null
            : GetDeniedReasonText(interaction.DeniedReason, includeCooldown: false);
        item.TooltipEnabled = !string.IsNullOrWhiteSpace(item.TooltipText);
    }

    private void OnInteractionHover(ItemList.ItemListHoverEventArgs args)
    {
        if (_hoveredInteractionIndex == args.ItemIndex)
            return;

        _hoveredInteractionIndex = args.ItemIndex;
        ItemInteractions.HideTooltip();
    }

    private Control? SupplyInteractionTooltip(Control sender)
    {
        if (sender != ItemInteractions)
            return null;

        if (!TryGetHoveredInteraction(out var interaction))
            return null;

        var tooltipText = GetInteractionTooltipText(interaction);
        if (string.IsNullOrWhiteSpace(tooltipText))
            return null;

        var tooltip = new Tooltip
        {
            Text = tooltipText,
        };

        return tooltip;
    }

    private bool TryGetHoveredInteraction(out ERPInteractionEntryState interaction)
    {
        interaction = default!;

        var mousePosition = ItemInteractions.GetLocalPosition(ItemInteractions.UserInterfaceManager.MousePositionScaled);
        foreach (var item in ItemInteractions)
        {
            if (item.Region == null || !item.Region.Value.Contains(mousePosition))
                continue;

            if (item.Metadata is not ERPInteractionEntryState hoveredInteraction)
                return false;

            interaction = hoveredInteraction;
            return true;
        }

        return false;
    }

    private string? GetInteractionTooltipText(ERPInteractionEntryState interaction)
    {
        var includeCooldown = _timing.CurTime < CooldownEndTime;
        if (!includeCooldown && interaction.Enabled)
            return null;

        return GetDeniedReasonText(interaction.DeniedReason, includeCooldown);
    }

    private static string? GetDeniedReasonText(ERPInteractionDeniedReason deniedReason, bool includeCooldown)
    {
        var reasons = new List<string>();

        if (includeCooldown)
            reasons.Add(Loc.GetString("erp-ui-denied-reason-cooldown"));

        if (deniedReason.HasFlag(ERPInteractionDeniedReason.NeedUserUncovered))
            reasons.Add(Loc.GetString("erp-ui-denied-reason-need-user-uncovered"));

        if (deniedReason.HasFlag(ERPInteractionDeniedReason.NeedTargetUncovered))
            reasons.Add(Loc.GetString("erp-ui-denied-reason-need-target-uncovered"));

        if (deniedReason.HasFlag(ERPInteractionDeniedReason.WrongUserSex))
            reasons.Add(Loc.GetString("erp-ui-denied-reason-wrong-user-sex"));

        if (deniedReason.HasFlag(ERPInteractionDeniedReason.WrongTargetSex))
            reasons.Add(Loc.GetString("erp-ui-denied-reason-wrong-target-sex"));

        if (reasons.Count == 0)
            return null;

        return string.Join('\n', reasons);
    }

    private static string FormatCooldown(TimeSpan timeLeft)
    {
        if (timeLeft.TotalSeconds >= 60)
            return $"{(int) timeLeft.TotalMinutes}:{timeLeft.Seconds:00}";

        return Loc.GetString("erp-ui-time-seconds",
            ("seconds", Math.Max(1, (int) Math.Ceiling(timeLeft.TotalSeconds))));
    }
}
