// <auto-generated />
using System;
using Content.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Content.Server.Database.Migrations.Sqlite
{
    [DbContext(typeof(SqliteServerDbContext))]
    [Migration("20260422234308_AddERPAndBarkFields")]
    partial class AddERPAndBarkFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Content.Server.Database.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<float?>("BarkPitch")
                        .HasColumnType("REAL")
                        .HasColumnName("bark_pitch");

                    b.Property<string>("BarkProto")
                        .HasColumnType("TEXT")
                        .HasColumnName("bark_proto");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("char_name");

                    b.Property<string>("ERPConsent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("erp_consent");

                    b.Property<string>("EyeColor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("eye_color");

                    b.Property<string>("FacialHairColor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("facial_hair_color");

                    b.Property<string>("FacialHairName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("facial_hair_name");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("flavor_text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hair_color");

                    b.Property<string>("HairName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hair_name");

                    b.Property<string>("HeadshotUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("headshot_url");

                    b.Property<float?>("HighBarkVar")
                        .HasColumnType("REAL")
                        .HasColumnName("high_bark_var");

                    b.Property<float?>("LowBarkVar")
                        .HasColumnType("REAL")
                        .HasColumnName("low_bark_var");

                    b.Property<byte[]>("Markings")
                        .HasColumnType("jsonb")
                        .HasColumnName("markings");

                    b.Property<bool>("NonCon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("non_con");

                    b.Property<string>("OOCNotes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ooc_notes");

                    b.Property<int>("PreferenceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preference_id");

                    b.Property<int>("PreferenceUnavailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pref_unavailable");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sex");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("skin_color");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<int>("SpawnPriority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("spawn_priority");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("species");

                    b.Property<string>("Voice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("voice");

                    b.HasKey("Id")
                        .HasName("PK_profile");

                    b.HasIndex("PreferenceId")
                        .HasDatabaseName("IX_profile_preference_id");

                    b.HasIndex("Slot", "PreferenceId")
                        .IsUnique();

                    b.ToTable("profile", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
