// SPDX-FileCopyrightText: 2026 Casha
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._FreakyStation;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FreakyStation;

[GenerateTypedNameReferences]
public sealed partial class ItemColorizerWindow : FancyWindow
{
    public ItemColorizerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ItemColorizerBoundUserInterfaceState state)
    {
        SelectedItemLabel.Text = state.ItemName ?? Loc.GetString("item-colorizer-window-no-item");
        ColorPicker.Color = state.CurrentColor;
        ApplyButton.Disabled = state.ItemName == null;
    }
}
